vitejs/vite-ecosystem-ci

.github/workflows/vitest.yml, vitest/.gitignore, vitest/integration-test.sh
Adds Vitest running the basic core suite. We can't run the whole Vitest CI because it is currently checking a lot of projects, and at least locally it fails with vite-ruby. So this isn't a good test for Vitest itself. Core seems enough
@dominikg adding a new project was straightforward, but we should discuss later how to abstract some of the boilerplate. Maybe an action could be created at least for all pnpm projects
Maybe we could also have the vite repo at root instead of having to clone it in each of the folders for local testing
=> feat: add vitest

svelte/index.js, utils.js, vitest/index.js
I think this is compact enough now 😃 
```js
import { resolve } from 'path'
import { runInRepo } from '../utils.js'
export async function test({ workspace }) {
await runInRepo({
repo: 'git@github.com:vitest-dev/vitest',
folder: resolve(workspace, 'vitest'),
build: 'build',
test: 'test:run',
verify: true,
})
}
```
=> refactor: simplify runInRepo

iles/index.js, index.js, utils.js
Adds [iles](https://github.com/ElMassimo/iles) to the Ecosystem CI
@ElMassimo, could you add a script that runs the iles CI without watch mode? Something like `test:ci` or `test:run`. You aren't seeing this issue because Vitest automatically disables watch mode in CI, but when we test this locally we still need it. We need to check why using `test run` as the script isn't working (maybe we should remove zx and use execa)
There are some failing tests, but I want to push this one so we can start playing. @ElMassimo, for reference, if you get this branch and run `nr test iles` it is going to clone vite, build latest, clone iles, build and verify that test are passing (here it fails now), then use pnpm overrides to set iles to use the local vite, and run the tests again. There will be an …
=> feat: iles

.github/workflows/ecosystem-ci.yml, index.js, utils.js
setup a new ci job that uses a 2-stage build-test
stage 1: build vite and upload result
stage 2: matrix that downloads stage1 result and runs suites in parallel
some changes to support all this on github ci like switching to https, using shallow clones and additional script args
=> feat: parallel jobs

.github/workflows/ecosystem-ci.yml, ecosystem-ci.js, tests/iles.js, tests/svelte.js, tests/vitepress.js, tests/vitest.js, tests/windicss.js, utils.js
This PR contains a new command `node ecosystem-ci.js bisect` which automates bisecting a commit range with a set of suites.
It also changes the main ecosystem-ci.yml to not upload/download a pre-built vite, as this doesn't work reliably. Instead each job of the matrix builds vite itself
=> feat: bisect / fix: ci

.prettierrc.json, package.json, pnpm-lock.yaml, tests/marko.ts, tests/nuxt-framework.ts, utils.ts
add support for npm and yarn.
add nuxt-framework (yarn) and marko (npm) as examples.
note: marko fails for vite 2.8.0-beta.5
=> feat: support multiple package managers

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/laravel.ts
This PR adds a suite for https://github.com/innocenzi/laravel-vite. 
It only runs the plugin tests, not all tests, because they require PHP too. But they don't depend on Vite itself so it's fine.
I've added `laravel` to both workflows, tell me if I'm missing something
=> feat: add laravel suite

tests/vitest.ts
See https://github.com/vitest-dev/vitest/pull/669
=> fix(vitest): --allowOnly

tests/svelte.ts, tests/vitest.ts
for some reason the '--' in vitest is working when executing it from a local shell but not when it's run from inside ecosystem-ci.ts via execa.
=> fix: test scripts

tests/telefunc.ts, tests/vite-plugin-ssr.ts, types.d.ts, utils.ts
The `pnpm run setup` step is needed to initialize the `libframe` Git submodule at https://github.com/brillout/vite-plugin-ssr and https://github.com/vikejs/telefunc.
=> feat: add vite-plugin-ssr test suite, telefunc test suite, and a new option `beforeInstall`

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/hydrogen.ts
The problem with Hydrogen unit tests was related to terminal color characters being removed, thus failing to match existing snapshots.
Should colors be enabled by default?
=> feat: enable Hydrogen

tests/telefunc.ts, tests/vite-plugin-ssr.ts
Both projects use `master` instead of `main`
=> fix: master branch for vite-plugin-ssr and telefunc

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/astro.ts
let's get this working now that astro is on pnpm :partying_face: 
`pnpm test astro --release 2.8.6` (uses vite release from npm)  fails on test step with
```shell
packages/webapi test:   1) Uncaught error outside test suite
packages/webapi test:   0 passing (335ms)
packages/webapi test:   1 failing
packages/webapi test:   1) Uncaught error outside test suite:
packages/webapi test:      Uncaught Workerpool Worker terminated Unexpectedly
packages/webapi test:     exitCode: `0`
packages/webapi test:     signalCode: `null`
packages/webapi test:     workerpool.script: `/home/dominikg/develop/vite-ecosystem-ci/workspace/astro/astro/node_modules/.pnpm/mocha@9.2.0/node_modules/mocha/lib/nodejs/worker.js`
packages/webapi test:     spawnArgs: …
```
=> feat: add astro

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
20min, recent successful runs had <10min, double time should be plenty
=> ci: add timeout to test runs to prevent hanging runs for 6h

utils.ts
this change means ecosystem-ci will no longer work for 2.9 series.  is that ok or should there a version switch?
=> fix: update to changes in vite package.json scripts

utils.ts
This PR adds core plugins to `pnpm.overrides` when `--release` isn't specified. This solves potential plugin compatibility problems in tests except when `--release` is used. We suggest using `--tag` when testing against alpha and beta releases.
=> feat: add core plugins to pnpm.overrides when --release isn't specified

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/storybook.ts
This passes locally when using `yarn test storybook --release 2.9.9`.
=> Add storybook/builder-vite

tests/vite-plugin-ssr.ts
The vite-plugin-ssr 0.4.0 branch's CI now works with both `2.9.10` and `3.0.0-alpha.9`.
For Vite 2, it needs to be `>=2.9.10` (because `configurePreviewServer()` is required).
For `3.0.0-alpha.9`, `@vitejs/react@2.0.0-alpha.2` needs to be used. I quickly checked and `vite-ecosystem-ci` seems to also override `@vitejs/react` but let me know if there is something I should do.
Also, the `0.4.0` branch uses pnpm v7.
=> fix: use vite-plugin-ssr Vite 3 compatible branch

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
Use the new `inputs` context from https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/
Don't think it would be deprecated ever, but the new syntax should be more searchable in github docs.
=> chore: use inputs context

tests/astro.ts
The Astro folks started a `vite-3` branch. It fails, but better to get it already hook up in vite-ecosystem-ci so we get a good picture of the state of the ecosystem
- https://github.com/withastro/astro/pull/3570
=> feat: astro vite-3 branch

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/vite-setup-catalogue.ts, types.d.ts, utils.ts
Adds https://github.com/sapphi-red/vite-setup-catalogue which contains some minimal setup examples.
refs https://github.com/vitejs/vite/pull/8650
=> feat: add vite-setup-catalogue

utils.ts
`@types/node` is actually an implicit peer dependency of Vite.
So I overrode it with the version from the Vite project dependencies.
This fixes the most recent iles CI failure.
=> fix: override `@type/node` to ensure consistent types

tests/marko.ts
Marko installs esbuild in its repo, in parallel to vite.
But if the lockfile contains an esbuild version that isn't the same as
the one that Vite depends on, there might be type incompatibilities
when type-checking the `esbuildOptions` field in vite config.
This fixes the most recent Marko CI failure.
https://github.com/vitejs/vite-ecosystem-ci/runs/7087966647?check_suite_focus=true#step:7:291
=> fix: override esbuild version in marko test

utils.ts
Fixes the most recent Nuxt and Storybook CI failure.
It's because Yarn seems not to follow the symlinks created by PNPM.
=> fix: resolve realpaths of overrides that points to a package inside `node_modules`

tests/storybook.ts
We've merged support for vite 3 into main and released a beta of @storybook/vite-builder: https://github.com/storybookjs/builder-vite/releases/tag/v0.2.0-beta.0
So, we can test against main now.
=> Test storybook against main branch

tests/rakkas.ts
I'm nearing a release so I've been adding a lot more tests that have little or no relation to Vite itself. This PR is for running a smaller subset of the Rakkas CI.
=> chore(rakkas): run a smaller subset of all tests

tests/astro.ts
The Astro team just merged our Vite 3 upgrade. Time to test against main again 🥳
=> chore: move Astro ecosystem branch back to `main`

.github/workflows/ecosystem-ci.yml
`ecosystem-ci-selected.yml` uses `-` for list but `ecosystem-ci.yml` was using `[]` for list.
https://github.com/vitejs/vite-ecosystem-ci/blob/ae0d8e9ddb3f3efddbd50ff10b17457f5caed975/.github/workflows/ecosystem-ci-selected.yml#L27-L46
This PR changes `ecosystem-ci.yml` to use `-` to make user a bit easier to add a suite.
=> chore: use same syntax for list

tests/marko.ts
marko's Vite 3 support has landed (https://github.com/marko-js/vite/pull/21).
That PR removes `npm run mocha` and thus the test was failing.
https://github.com/marko-js/vite/pull/21/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L85-R89
This PR changes marko to use `npm run test` instead.
With this change marko passes 🎉 
https://github.com/sapphi-red/vite-ecosystem-ci/runs/7453521897?check_suite_focus=true
=> fix: marko test command

discord-webhook.ts
`git rev-parse --short HEAD` fails when `refType` is `release`.
https://github.com/vitejs/vite-ecosystem-ci/runs/7433372208?check_suite_focus=true#step:8:16
=> fix: don't run getPermanentRef when refType is release

utils.ts
discord webhook sends a link to commit log. It uses `git rev-parse --short HEAD` to obtain the commit hash.
But this should be `git show-ref --hash --abbrev HEAD`.
For example, https://github.com/vitejs/vite/commits/0b083ca is 404 but https://github.com/vitejs/vite/commits/0b083ca8 isn't.
=> fix: use abbrev for perm ref

utils.ts
`git show-ref --hash --abbrev HEAD` fails when `refType` is tag. I'm not sure why but it seems to be because of the detached head?
https://github.com/vitejs/vite-ecosystem-ci/runs/7487866389?check_suite_focus=true#step:8:15
I checked `git show-ref --hash --abbrev` works. But it returns multiple lines.
This PR uses `git log -1 --pretty=format:%h` instead. I tested this with https://github.com/vitejs/vite/commits/0b083ca8 too.
=> fix: getPermanentRef for refType=tag

tests/ladle.ts
Looks like https://github.com/tajo/ladle renamed default branch to `main`, which is failing CI.
=> chore: update ladle branch

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
this should prevent deno install errors from messing up tests that do not require deno
=> fix: use v1.x for deno and continue if install fails

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, discord-webhook.ts, ecosystem-ci.ts, types.d.ts, utils.ts
This PR adds support for using repository other than vitejs/vite.
Example run: https://github.com/sapphi-red/vite-ecosystem-ci/runs/8059305521?check_suite_focus=true#step:7:11
closes  #33
=> feat: vite repo

tests/vite-plugin-ssr.ts
Vite-plugin-ssr's repository doesn't need the `setup` step anymore.
=> fix: update vite-plugin-ssr integration

tests/svelte.ts
vite-plugin-svelte recently changed the way it uses playwright from platform browser to manual download
=> fix(svelte): install playwright chromium before testing 

package.json, pnpm-lock.yaml, tests/svelte.ts
Attempt to fix failing svelte test, looks like `vite-plugin-svelte` and `svelte-kit` are using different versions of `svelte` causing errors. This PR ensures both are the same. [Discord discussion](https://discord.com/channels/804011606160703521/1030360762666979338/1032953953106788362).
=> fix(svelte): override svelte as latest

tests/svelte.ts
This would have caught https://github.com/vitejs/vite/issues/10656  
The additional runtime is only a few seconds.
Switched from build:ci to build in v-p-s because sveltekit check does depend on types of v-p-s too.
=> feat: run lint and check scripts in svelte repos

tests/svelte.ts
and prevent vite types/node override causing a mismatch
sveltekit isn't using a build step internally for a while now and a recent PR removed the root build script from it's package.json so we no longer need to call it here.
the override for types/node is needed to avoid an error when calling `check`. Vite currently uses @types/node@17, which is incompatible to kit and causing a check error in a test file that uses webcrypto.subtle 
see https://discord.com/channels/804011606160703521/1036513246288556062/1036561228010639380 and https://github.com/vitejs/vite-ecosystem-ci/actions/runs/3358813763/jobs/5566222879#step:7:1328
=> fix: remove build script for sveltekit 

.eslintrc.cjs, ecosystem-ci.ts, package.json, pnpm-lock.yaml, utils.ts
Switched to `eslint-plugin-n` that is a maintained fork of `eslint-plugin-node`. (`eslint-plugin-node` was depending on the vulnerable `minimatch`)
This PR will fix the audit CI fail in #139.
=> chore: switch to eslint-plugin-n

package.json, pnpm-lock.yaml, utils.ts
With this PR, command output will be grouped when running in GitHub Actions.
Examples:
https://github.com/sapphi-red/vite-ecosystem-ci/actions/runs/3356302400/jobs/5561270954
https://github.com/sapphi-red/vite-ecosystem-ci/actions/runs/3356341804/jobs/5561338930
=> feat: group command output in GitHub Actions

ecosystem-ci.ts, tests/svelte.ts, tests/vitepress.ts, types.d.ts, utils.ts
pass `viteMajor` in runOptions for tests to be able to switch to a different branch that supports this major version
=> feat: vite major option

.github/workflows/ecosystem-ci-from-pr.yml
in runs triggered by PR comments from vite repo
=> fix: use correct suite names for svelte tests

utils.ts
replaying cached commands might lead to hard to track down errors
=> fix: set env flag to disable turbo.build caching globally. 

tests/sveltekit.ts, utils.ts
remove extra override from sveltekit test
=> fix: disable types/node override for vite-4+

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, package.json
Using Node.js 18 instead of Node.js 16 should fix VPS's CI.
Also potentially the Laravel CI since its TS error is also about Node.js (CC @timacdonald).
Currently failing eco CI: https://github.com/vitejs/vite/pull/11110#issuecomment-1330110858
=> fix: use Node.js 18

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/vite-plugin-react.ts, tests/vite-plugin-vue.ts
@dominikg is the `beforeTest` step necessary? I copied it from your vite-plugin-svelte test definition.
=> feat: vite-plugin-vue and vite-plugin-react

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, package.json, utils.ts
~~only do it for existing directories and use relative path~~
- use more specific local directory check and make sure the path is absolute
- use pnpm 7.18.1 for ecosystem-ci itself 
- change packageManager constraint in package.json of test project if it would use pnpm 7.18.0
=> fix: automatic file: protocol handling

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
some suites (eg sveltekit) scratch the limit and it can lead to fails
=> chore: relax timeout to 30min

utils.ts
We need `pathToFileURL` before passing a path to `import` for windows.
=> fix: use pathToFileURL for windows

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, discord-webhook.ts
I guess this error is happening because it reached the rate limit.
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/3846033998/jobs/6550867591#step:9:16
`secrets.GITHUB_TOKEN` is now used for the GitHub API call to reduce the rate limit error happening.
I also added some logs to understand the error, in case it happens in future.
=> fix: use token for github api call

utils.ts
and editorconfig to prevent leakage
This had caused the failure in sveltekit, that didn't specify the `"root":true` option and as a result vite-ecosystem-ci 's own rules were applied too and the test failed. To prevent our own env from leaking into the test environments in workspace, this PR adds config files to the workspace to stop traversal for eslint and editorconfig (may be used by prettier)
=> fix: init workspace dir and add root option for eslintrc

utils.ts
while checking out #195  i noticed that commands were run with pnpm all the time, even when the local pm was different.
It didn't cause errors from what i've seen, but we should use the tools the projects have defined
=> fix: use correct dir to detect package manager in use

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/unocss.ts
Follow up to https://github.com/vitejs/vite-ecosystem-ci/pull/209, unocss should cover the code paths that we lost after removing windi
=> feat: add unocss

builds/vite-plugin-svelte.ts, tests/sveltekit.ts
the package was recently split, it used to be an internal second plugin in v-p-s
=> fix: add override for new vite-plugin-svelte-inspector

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/analogjs.ts
Hello!
This pr adds AnalogJS to the vite-ecosystem-ci.
It's still WIP as the oustanding pr ([#416](https://github.com/analogjs/analog/pull/416)) to migrate AnalogJS to `pnpm` isn't merged yet. 
But all the tests should work already.
=> feat: add analogjs test

tests/nx.ts, tests/vitest.ts, types.d.ts, utils.ts
third option to #233 and #234
being more explicit with an object allows us to get rid of the split that was previously used for scripts with args
=> fix: add new Task type for scripts with args so that we can pass them to ni

tests/nuxt.ts
see https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6218411148/job/16874862943#step:8:1049
it complains about installed playwright bin so  install that (see also sveltekit / vite-plugin-svelte doing the same)
=> chore: run playwright install to avoid nuxt test error

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/vike.ts
The vite-plugin-ssr project has been renamed to Vike.
- [vike.dev](https://vike.dev)
- [github.com/vikejs/vike](https://github.com/vikejs/vike)
=> vite-plugin-ssr renamed to Vike

discord-webhook.ts, utils.ts
`git log -1 --pretty=format:%h` returns an ambiguous ref.
https://discord.com/channels/804011606160703521/1162083505812025384/1162318471745515541
=> fix: use non-truncated ref for links in discord

tests/histoire.ts, tests/ladle.ts, tests/nuxt.ts, tests/sveltekit.ts, tests/vite-plugin-pwa.ts, tests/vite-plugin-react-swc.ts, tests/vite-plugin-svelte.ts, tests/vitepress.ts, utils.ts
we are not going to run ecosystem-ci on vite-3 anymore so this is no longer needed. Hopefully we won't have to reintroduce similar checks for vite4/5 :crossed_fingers:
=> chore: remove special handling for vite-3

.github/workflows/ecosystem-ci-from-pr.yml
Ported some changes from https://github.com/vuejs/ecosystem-ci which would be useful for us
- https://github.com/vuejs/ecosystem-ci/commit/8771f9c6ebe16045733fce034a13170a14eb3614 + fixes
- https://github.com/vuejs/ecosystem-ci/commit/8aa3eae56534890ee0c3320e1e8eade91d7df85a
=> Port changes from vue ecosystem ci

tests/marko.ts
Not sure why it's failing recently, but maybe we should install chromium before testing like the other frameworks.
Failed run: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6583609019/job/17886920362#step:8:744
=> fix(marko): install playwright chromium before testing

tests/nx.ts, utils.ts
This makes nx pass: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6728289738/job/18287407127
=> fix(nx): skip rollup overrides

tests/sveltekit.ts
vite 5 support in sveltekit is going to be in version-2.
=> chore(tests): switch sveltekit to version-2 branch

tests/sveltekit.ts
version-2 has been merged. 
Draft state bc current default is still master, waiting for the rename to happen
=> chore: update sveltekit default branch

README.md
Since Remix is currently using Yarn (albeit with plans to move to pnpm) I initially thought Remix would first need to migrate to pnpm before adding a test to this repo based on this line in the readme, but was later told that this is outdated.
=> docs: remove note about pnpm-focused utils

utils.ts
so that it works even when the test project is not using pnpm
see https://discord.com/channels/804011606160703521/1196724390998577203/1196758463158693899
=> fix: ensure pnpm binary is only called in vite dir to get vite package info

utils.ts
this can make installation slower but also ensures correct versions
=> fix(pnpm): do not prefer local, it could be tainted

tests/laravel.ts
@dominikg let's set the 1.x branch ourselves, and re-discuss with the Laravel folks with a real fail in our hands.
=> fix: laravel 1.x branch

.github/workflows/ecosystem-ci-from-pr.yml
Only show results in table format when there are fails. If both the current suite and the previous one are green, then just list the current suites results as a single line to save space.
We could add an "All green! 🎉" but maybe it will end up bothering us.
The change is untested 😬, but seems simple enough. Please review with care 🙏🏼
=> feat: condensed table for pr result

tests/nuxt.ts
Updating to vite v5.2.0 seems to have a regression for Nuxt, but only in development. (See https://github.com/nuxt/nuxt/pull/26399.)
This enables running dev tests in vite ecosystem CI in future.
=> fix: also run nuxt dev fixtures

builds/vite-plugin-svelte.ts, tests/vite-plugin-svelte.ts
until main branch has stabilized more
vite-plugin-svelte main branch works on svelte@next now but thats still undergoing changes causing more fails. 
@latest lives in v3 branch so switch to that
=> fix: switch vite-plugin-svelte to v3 branch

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, .npmrc, package.json, pnpm-lock.yaml
add package-manager-strict=false to prevent pnpm itself from checking the packageManager field. Set some corepack env vars to ensure strictness but keep it at bay.
The sha hash in our own packageManager field is recommended by corepack to ensure integrity. to update it, run `corepack up`.   
unfortunately the hash itself seems to not be the same as integrity in the npm package data :/ https://github.com/nodejs/corepack/issues/316  , so verification has to be done in another way
oneliner that shows the hash of the downloaded tgz
```
curl `npm info pnpm@9.1.4 dist.tarball` | sha512sum
```
=> chore: update to pnpm9 and disable package-manager-strict

utils.ts
Example: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/9476969819/job/26110768545
The execa std errors are hard to read, especially that we had already piped the output the the main process, so I don't think we need the props anymore.
=> fix: delete execa std props

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/vuepress.ts
This PR added [vuepress](https://github.com/vuepress/core) to test suite.
I've tested locally and it's working well.
=> feat: add vuepress test

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/vite-environment-examples.ts
As discussed with @patak-dev, this PR adds https://github.com/hi-ogawa/vite-environment-examples to ecosystem ci.
I verified the test passes locally by:
```sh
pnpm tsx ecosystem-ci.ts --branch v6/environment-api vite-environment-examples
```
=> feat: add vite-environment-examples

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci.yml
I believe @patak-dev has contacted @csr632 (who maintains `vite-plugin-react-pages`) before but it's not clear whether the CI will be fixed. It has been failing since June and it would be good to prevent resources spent on a known fail.
=> chore: disable vite-plugin-react-pages

utils.ts
Allow colors in CI so it's easier to read the logs, and possibly fix the Vike fail
=> fix: allow colors in CI

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci.yml, tests/storybook.ts
Supersedes https://github.com/vitejs/vite-ecosystem-ci/pull/307 and https://github.com/vitejs/vite-ecosystem-ci/pull/137.
Second attempt: I have provided some scripts for the ecosystem-ci in Storybook's monorepo. I had to introduce a `before-test` script on our side to copy over the resolutions field from the root's `package.json` to the package.json of the created sandbox: https://github.com/storybookjs/storybook/pull/27518/files, but this should be fine I guess.
=> feat: add Storybook back to vite-ecosystem-ci

.github/workflows/ecosystem-ci-from-pr.yml
I was wondering why it's not appearing in the list https://github.com/vitejs/vite/pull/16471/#issuecomment-2315399812 and I think I just forgot to add it to one more place :sweat_smile:
=> fix: add vite-environment-examples to execute-all

.github/workflows/ecosystem-ci-from-pr.yml
We are missing two projects in the from-pr list (that we test in the regular run)
=> feat: add redwoodjs and vuepress to from-pr list

tests/vuepress.ts
Probably needs to add this for vuepress as well.
Failed run: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/11098468509/job/30834087016#step:8:1727
=> fix(vuepress): install playwright chromium before testing

builds/vite-plugin-svelte.ts, tests/vite-plugin-svelte.ts
to avoid errors from mismatched svelte versions
=> fix: svelte5 has been released, switch vite-plugin-svelte to main

tests/sveltekit.ts
Using svelte 5 with svelte kit is causing type errors.
https://discord.com/channels/804011606160703521/928398470086291456/1299236704510672897
=> fix: use svelte 4 for sveltekit for now

tests/waku.ts
This tries to use the new waku script for running the test cases in vite-ecosystem-ci!
=> fix(waku): vite-ecosystem-ci script

.github/workflows/ecosystem-ci-from-pr.yml
continues #339 to fix https://github.com/vitejs/vite-ecosystem-ci/pull/339#issuecomment-2508076588
apparently + was not supported in that case!
=> fix: optional commit unexpected symbol 

.github/workflows/ecosystem-ci-from-pr.yml
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/12312778835/job/34365511239#step:9:11
=> fix: run get-ref in root if commit is specified

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/react-router.ts
Added a test for React Router. I've successfully run this test locally so I've also added it to the workflows.
Thanks as always for all of your hard work on the project 🙏
=> feat: add react-router test

tests/analogjs.ts
Beta is the default development branch for analogjs
=> ci: use beta branch for analogjs

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
same with #262 but for node 22
=> chore(ci): execute with node22

utils.ts
This error happens: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/12985510047/job/36210515231#step:8:27
From the example, it seems the passed argument should be like `${packageName}@${version}`.
https://www.npmjs.com/package/pacote#:~:text=pacote.manifest(%27foo%401.x%27)
=> fix: release type was not working

tests/waku.ts
waku only uses chromium for ecosystem-ci so let's skip installing other browsers
=> perf(waku): only install chromium

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
to avoid error from older corepack used by gh runner
see https://github.com/nodejs/corepack/issues/612#issuecomment-2631462297
(the same change in svelte-ecosystem-ci fixed this error:  https://github.com/vitejs/vite-ecosystem-ci/actions/runs/13193523934/job/36830669819#step:8:1243
=> fix(ci): manually add new signing keys to corepack 

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, utils.ts
telemetry is not useful in our case, might end up hurting perf and logging things we don't need or want.
If you know more of these for other tools (deno, node?) please share so they can be added.
sidenote: the CI env should be enough for these tools to not do it, but alas here we are.
=> fix: add environment variables to disable telemetry in turbo

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, package.json
the previous method of manually adding the keys to environment did not work and node 22.14 includes a newer corepack that fixes it
=> fix: force use of node 22.14+ to avoid corepack sig errors

tests/vike.ts
@brillout  
looks like vike tests require playwright browser install, added a script here to ensure it works. anything else that needs adaption? 
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/13363207623/job/37316256667#step:8:1973
=> vike tests use playwright and it complained install was missing

tests/sveltekit.ts
this helps shave some time off total suite time and reduces false positives when kit repo has failing checks on its own
=> chore: remove lint and reduce amount of checks from sveltekit tests

.github/workflows/ecosystem-ci-from-pr.yml
Migrated to https://github.com/actions/create-github-app-token from https://github.com/tibdex/github-app-token.
=> ci: migrate to official app token action

utils.ts
Enable retries for manifest fetch since it sometimes fails.
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/14505881712/job/40695132986#step:8:30
Retries are enabled by package managers already, so this aligns the behavior with them as well.
=> feat: retry manifest fetch

pnpm-lock.yaml, utils.ts
I encountered the 500 failure again: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/14791127150/job/41528331180#step:8:30
I checked the code and found that the property names in the types were wrong (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72671)
This PR fixes the property names.
refs #383
=> fix: correct retry option for manifest fetch

tests/waku.ts, utils.ts
To unblock https://github.com/vitejs/vite/pull/19996
=> feat: use Vite 6 for old Vitest

tests/react-router.ts, tests/waku.ts
To unblock https://github.com/vitejs/vite/pull/19996
These two projects use vite-node.
=> chore: set vite-node overrides for waku and react-router

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
#388 made failure results and skipped results to be not sent to discord. This PR fixes that.
`always() && condition` seems to be the way to do this.
https://github.com/search?q=%2Falways%5C(%5C)+%26%26%2F+language%3Ayaml&type=code
Probably this is how we can understand the behavior:
> I would have expected the default value of `if: success()` to be replaced with `if: <your_condition>`, but it's actually `if: success() && <your_condition>` _unless_ your condition includes one of the status functions
> — quoted from https://github.com/actions/runner/issues/491#issuecomment-660122693
=> fix: send failure / skipped results to discord

tests/react-router.ts, tests/waku.ts
This PR reverts #393
refs https://github.com/remix-run/react-router/pull/13781, https://github.com/vanilla-extract-css/vanilla-extract/pull/1605
=> chore: remove vite-node overrides

builds/vite-plugin-react.ts, tests/react-router.ts, tests/waku.ts
- Related https://github.com/vitejs/vite-plugin-react/issues/645
TODO
=> feat: override `@vitejs/plugin-rsc` on `waku` and `react-router`

tests/waku.ts
Waku should now pass on rolldown-vite https://discord.com/channels/804011606160703521/1364135135447879740/1401499077656580121
=> chore: remove rolldownViteExpectedFailureReason from waku

utils.ts
I didn't introduce yaml parser since we can read `pnpm config list --json --location project` for the same information. Yaml writing is still regex and hopefully this is robust enough. I confirmed `pnpm test vitepress` passes.
=> fix: properly merge overrides in pnpm-workspace.yaml
