svelte/index.js, utils.js, vitest/index.js
defaults for repo and folder, removing the need for another import
=> refactor: runInRepo defaults

.eslintrc.cjs, .github/renovate.json5, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, .prettierrc.json, README.md, ecosystem-ci.js, package.json, pnpm-lock.yaml, tests/iles.js, tests/svelte.js, tests/vitepress.js, tests/vitest.js, tests/windicss.js, utils.js
slight refactor to avoid TLA (eslint doesn't like it and bringing in babel for that didn't feel right)
=> chore: prettier eslint lint-staged

README.md, package.json, pnpm-lock.yaml
=> fix: switch from tsm to esmo to avoid broken --help. see #22

tests/hydrogen.ts
=> feat: hydrogen

utils.ts
See https://github.com/antfu/ni/pull/63, that introduced a new agent type `yarn@berry`
=> fix: support yarn@berry detected agent

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
@dominikg the list is getting interesting now :)
=> feat: enable vite-plugin-ssr and telefunc

tests/iles.ts, utils.ts
to avoid invalid image error for bench.png
=> fix: run git lfs install && git lfs pull before iles test 

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
Avoid Astro report issues, we may avoid requiring deno locally afterward
=> feat: add deno to workflows

tests/astro.ts
See https://github.com/withastro/astro/pull/3093/
Thanks for adding the script @matthewp!
Doing the PR so we can test and release Vite 2.9.2
=> chore: use astro test:vite-ci script

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, .npmrc, package.json, pnpm-lock.yaml
now that vite main is on pnpm7, switch here too
=> chore: switch to pnpm7 and enforce it

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, .gitignore, package.json
lets see how it handles things
=> chore: update pnpm again and reenable schedule for projects not using pnpm6

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
=> chore: enable corepack on ci

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/rakkas.ts
Adds [Rakkas](https://github.com/rakkasjs/rakkasjs) the test suite.
**REQUIRES #76 FOR `vite@3` TESTS TO PASS!**
=> feat: add rakkas

tests/svelte.ts
=> fix: use vite-3 branch for svelte

tests/vitest.ts
See https://github.com/vitest-dev/vitest/tree/feat/vite-3, @sheremet-va is going to merge this branch once we release v3.
=> feat: point vitest to feat/vite-3 branch

tests/_selftest.ts, types.d.ts, utils.ts
and allow shelll scripts in command strings
closes #91
=> feat:  add beforeBuild and beforeTest to repo commands 

utils.ts
=> fix: fix detection of npm scripts with arguments

tests/ladle.ts
Wrong flag, should just work without it.
=> Remove failing --serial flag from ladle.ts

tests/svelte.ts
wait with merge until both vite-3 branches are merged in these repos, should happen today.
=> chore: update branches of svelte repo for vite 3 release

tests/nuxt-framework.ts
We should start testing main again:
- https://github.com/nuxt/framework/pull/5398
=> chore: nuxt back to main

.github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, discord-webhook.ts
Simplified the discord messages.
**desktop**
**mobile**
=> feat: polish discord message

tests/rakkas.ts
I'm switching to a model where `main` is the dev branch so updating the branch here.
=> chore: update Rakkas branch next -> main

.github/workflows/ecosystem-ci-from-pr.yml
See https://github.com/vitejs/vite/pull/9887.
(I'll later write descriptions there)
=> feat: run from PR comment

builds/vite-plugin-react.ts, builds/vite-plugin-svelte.ts, builds/vite-plugin-vue.ts, tests/iles.ts, tests/nuxt-framework.ts, tests/sveltekit.ts, tests/vite-plugin-ssr.ts, tests/vitepress.ts, types.d.ts, utils.ts
work in progress for now.
cc @brillout @sapphi-red 
if you have ideas how we could make this more streamlined i'm eager to hear them.
Maybe we should extend the vite build to include these by default of have a new run option ?
=> feat: common builds for framework plugins

utils.ts
before running bisect commands that fail on dirty
=> fix(bisect): revert changed done by vite build 

package.json, pnpm-lock.yaml, types.d.ts, utils.ts
this prevents errors where ni binary is not found in the project under test.
=> fix: use commands from ni directly instead of calling ni binary

utils.ts
and skip if not relevant for ecosystem-ci
see https://github.com/nuxt/nuxt/commit/434e2013e46d0795fa0341986e62950ace77178c
=> feat: add ECOSYSTEM_CI=true to env so that tests can check it

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/nx.ts
Added the `@nx/vite` package tests.
=> feat(tests): add Nx test suite

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, package.json, pnpm-lock.yaml
everything all at once so that we can see them working together (or not)
=> chore: update everything to latest

utils.ts
to make logs easier to read in github
=> feat: disable color coded output in terminals 

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
please be faster :pleading_face: 
fixes #248
=> chore(ci): execute with node20

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/remix.ts
Added a test for Remix + Vite.
Thanks so much for all the hard work on this project 🙏
=> feat: add Remix test

tests/vite-plugin-react-swc.ts, tests/vite-plugin-react.ts
This should failed, I will mark it as ready when the issue is fixed in the plugin, but I least now it will be check.
This is already done for the swc plugin
=> Run tsc in vite-plugin-react

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/remix.ts
They said moving to pnpm is on the table, so it is probably better we just wait here.
=> chore: disable remix until they move to pnpm

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci.yml
@markdalgleish worked out the issues, and Remix is green now: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/8338225881/job/22818181643
Let's start testing it as part of the full vite-ecosystem-ci runs 🎉
=> feat: enable remix as part of full runs

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/redwoodjs.ts
Adding some basic Redwood tests to the test suite
=> feat: add redwoodjs test

tests/redwoodjs.ts
Disabling NX cache as recommended by @dominikg
=> fix(redwood): Disable nx cache

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/waku.ts
This adds waku to the suite! 
Thank you so much 🙌
=> feat: waku

ecosystem-ci.ts
removing the options.repo from the pkg.pr.new since it's not needed!
=> fix: use vite main continiuous release

tests/rakkas.ts
https://github.com/puppeteer/puppeteer/issues/12818
https://github.com/puppeteer/puppeteer/pull/13196
=> fix(rakkas): disable apparmor restrictions on GitHub Actions for now

tests/vitepress.ts
to fix https://github.com/vitejs/vite-ecosystem-ci/actions/runs/12982345684/job/36202032900#step:8:1463
=> fix(vitepress): install playwright browser

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml, tests/one.ts
Got it set up and verified tests pass!
=> feat: add one framework

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
=> ci: set permissions to workflows

tests/vite-plugin-react.ts, utils.ts
See https://github.com/vitejs/vite-plugin-react/pull/439
=> feat(plugin-react): make tests pass with plugin-react-oxc

.github/workflows/ecosystem-ci-rolldown.yml, discord-webhook.ts
Run ecosystem-ci with rolldown-vite regularly on Tuesday and Thursday.
=> feat: run with rolldown-vite regularly

utils.ts
When running the script with a different branch from a previous run, the following error was happening:
```
$> git -c advice.detachedHead=false checkout main
error: pathspec 'main' did not match any file(s) known to git
```
This PR fixes that.
I tested this PR by first running `pnpm tsx ecosystem-ci.ts marko --repo vitejs/rolldown-vite --branch rolldown-vite`, then `pnpm tsx ecosystem-ci.ts marko --repo vitejs/rolldown-vite --branch main`.
=> fix: call `git remote set-branches` when running with a different branch from previous run

.github/workflows/ecosystem-ci-rolldown.yml, discord-webhook.ts, tests/astro.ts, tests/histoire.ts, tests/ladle.ts, tests/nuxt.ts, tests/one.ts, tests/qwik.ts, tests/react-router.ts, tests/storybook.ts, tests/sveltekit.ts, tests/vike.ts, tests/vite-plugin-cloudflare.ts, tests/vite-plugin-svelte.ts, tests/waku.ts
To make it easier to look at the results.
=> feat: show expected failures for rolldown-vite runs

.github/workflows/ecosystem-ci-from-pr.yml, .github/workflows/ecosystem-ci-rolldown.yml, .github/workflows/ecosystem-ci-selected.yml, .github/workflows/ecosystem-ci.yml
I don't think there's a way to exploit this as only trusted inputs are passed. But it's better to avoid it anyway.
=> refactor: avoid interpolation
